### ISSUE TITLE
Why not having the authentication process between Paymentrequest and Paymentresponse

### ISSUE THREAD

**Issue by CYV** [w3c/pisp-credit#4]
Foolowing Ian proposal to a better seamless user experience. On the chart sct016.pml, why not having the authentication of Alice jsut between the payment request and the payment response ?

**Comment by CYV** [comment]
I am not sure the design of Bank's API is compliant but we could investigate a bit.

**Comment by CYV** [comment]
a new flow chart in the wiki (sct017.pml): better user experience. Now we have to check if the DSP2 API is compliant with those flows !! (i am not confident)

**Comment by cyberphone** [comment]
@CYV This is OK but also introduces a _new_ question.  _Where_ does the client side code performing step 7-9 actually reside?

AFAICT, this code is _bank specific_ ruling out a pre-installed solution a la `basic-card`, effectively leaving us with the following choices:
- https://www.w3.org/TR/payment-handler/
- Google's proprietary Android Payment Request API

If I were going for Android, I would consider rethinking the whole scheme because needing bank-specific Apps is not such a great idea.  Google did not need that and neither do most of the Scandinavian schemes I have mentioned.  This (among many things), means _signing payment request data locally_ rather than relying on legacy on-line banking authentication solutions.  No, local signing will not work with the current STET PSD2 API but that is yet another question :-)

**Comment by cyberphone** [comment]
If this approach would be adopted, the work-item would AFAICT not depend on any specific additional browser support.  That is, it would rather be an "application" of the existing API making it less suitable for W3C standardization, particularly given the fact that there is no standardized PISP API.

The registered payment method `pisp-credit `wouldn't apply either.

**Comment by cyberphone** [comment]
If this issue isn't relevant anymore, I would consider closing it.

**Comment by ianbjacobs** [comment]
Closing this and await unified credit transfer spec with results of experiments with user experience.
